---
  accept:
    - application/json
  server:
    uri: localhost:3000
  routes:
    serviceUrl: 'https://dyicn1e62j3n1.cloudfront.net:443/1.0/'
    controllerRootUrl: '/api'
    apiVersion: '/v1/'
    geoLocationService: 'http://ip-api.com/json'
  logging:
    stdout:
      enabled: true
      level: debug
  port: 3000
  env: dev
